### ISSUE TITLE
Linting and Styling checks in pull requests

### ISSUE THREAD

**Issue by espipj** [espipj/Hacktoberfest-React-XP#7]
When contributors make their pull requests we need to make sure that the code doesn't have any linting problems and that follows the style applied by the prettier config file `src/.prettierrc.json`

## Solution
Using a CI tool i.e. Circle CI to do those checks

**Comment by mahowa** [comment]
Ill take this. Using husky to do checks before commits

**Comment by espipj** [comment]
Hey @mahowa that's great! 😺
